"""
gen_grass_blades.py — procedural grass blade OBJ generator

Generates ~1000 tapered quad blades randomly distributed over a patch,
inspired by:
  https://inria.hal.science/inria-00087776/PDF/RR-5960.pdf
  https://github.com/spacejack/terra

Coordinate system: Z-up (matches this ray tracer's scene convention).
  - Ground is the XY plane (Z=0).
  - Blades grow upward along +Z.
  - Patch is centered at the origin.

Blade geometry (per blade):
  - 2 triangles (1 tapered quad)
  - Base width 0.02m, tip width 0.005m
  - Height 0.15m
  - Random azimuth rotation
  - Slight forward lean (tip offset ~20% of height)
  - Normals computed per-triangle (flat shading)

Usage:
    python scripts/gen_grass_blades.py [--count 1000] [--patch 4.0] [--seed 42]
    Output: assets/meshes/grass_blades.obj
"""

import math
import random
import argparse
import os

def normalize(v):
    l = math.sqrt(sum(x*x for x in v))
    if l < 1e-10:
        return v
    return tuple(x / l for x in v)

def cross(a, b):
    return (
        a[1]*b[2] - a[2]*b[1],
        a[2]*b[0] - a[0]*b[2],
        a[0]*b[1] - a[1]*b[0],
    )

def tri_normal(v0, v1, v2):
    e1 = (v1[0]-v0[0], v1[1]-v0[1], v1[2]-v0[2])
    e2 = (v2[0]-v0[0], v2[1]-v0[1], v2[2]-v0[2])
    return normalize(cross(e1, e2))

def generate_blades(count, patch_size, seed):
    rng = random.Random(seed)
    half = patch_size / 2.0

    base_width = 0.02
    tip_width  = 0.005
    height     = 0.15
    lean       = 0.03    # max forward lean at tip (meters)

    verts   = []  # (x, y, z)
    normals = []  # (nx, ny, nz)
    uvs     = []  # (u, v)
    faces   = []  # list of (v0,v1,v2, n, uv0,uv1,uv2) 1-indexed

    for _ in range(count):
        # Random position in the patch
        px = rng.uniform(-half, half)
        py = rng.uniform(-half, half)

        # Random azimuth: blade's "forward" direction (the tilt direction)
        theta = rng.uniform(0, 2 * math.pi)
        fwd = (math.cos(theta), math.sin(theta))   # XY forward direction
        perp = (-math.sin(theta), math.cos(theta)) # XY perpendicular (width axis)

        # Slight random lean at the tip (0.5x–1.5x of max lean)
        lean_scale = rng.uniform(0.5, 1.5)
        tip_lean_x = fwd[0] * lean * lean_scale
        tip_lean_y = fwd[1] * lean * lean_scale

        # Slight random height variation
        h = height * rng.uniform(0.8, 1.2)

        hb = base_width / 2.0
        ht = tip_width  / 2.0

        # 4 blade vertices
        bl = (px - perp[0]*hb,       py - perp[1]*hb,       0.0)   # base left
        br = (px + perp[0]*hb,       py + perp[1]*hb,       0.0)   # base right
        tr = (px + perp[0]*ht + tip_lean_x, py + perp[1]*ht + tip_lean_y, h)  # tip right
        tl = (px - perp[0]*ht + tip_lean_x, py - perp[1]*ht + tip_lean_y, h)  # tip left

        # Normals (flat, one per triangle, averaged at shared verts is fine for now)
        n1 = tri_normal(bl, br, tr)
        n2 = tri_normal(bl, tr, tl)
        # Use the average of the two face normals as a stable blade normal
        n_avg = normalize((n1[0]+n2[0], n1[1]+n2[1], n1[2]+n2[2]))

        # Record vertex base index (1-indexed in OBJ)
        vi = len(verts) + 1
        ni = len(normals) + 1
        ti = len(uvs) + 1

        verts += [bl, br, tr, tl]
        normals += [n_avg]
        uvs += [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]

        # Triangle 1: bl, br, tr
        faces.append((vi+0, vi+1, vi+2, ni, ti+0, ti+1, ti+2))
        # Triangle 2: bl, tr, tl
        faces.append((vi+0, vi+2, vi+3, ni, ti+0, ti+2, ti+3))

    return verts, normals, uvs, faces


def main():
    parser = argparse.ArgumentParser(description="Generate grass blade OBJ")
    parser.add_argument("--count",  type=int,   default=1000,  help="Number of blades")
    parser.add_argument("--patch",  type=float, default=4.0,   help="Patch side length (m)")
    parser.add_argument("--seed",   type=int,   default=42,    help="Random seed")
    parser.add_argument("--output", type=str,
                        default=os.path.join(os.path.dirname(__file__),
                                             "..", "assets", "meshes", "grass_blades.obj"),
                        help="Output OBJ path")
    args = parser.parse_args()

    print(f"Generating {args.count} grass blades over {args.patch}m patch (seed={args.seed})...")
    verts, normals, uvs, faces = generate_blades(args.count, args.patch, args.seed)

    out_path = os.path.normpath(args.output)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Procedural grass blades — generated by gen_grass_blades.py\n")
        f.write(f"# {args.count} blades, {args.patch}m patch, seed {args.seed}\n")
        f.write("# Coordinate system: Z-up. Ground at Z=0.\n")
        f.write("o grass_blades\n\n")

        f.write("# Vertices\n")
        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        f.write("\n# Normals\n")
        for n in normals:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")

        f.write("\n# UV coordinates\n")
        for uv in uvs:
            f.write(f"vt {uv[0]:.4f} {uv[1]:.4f}\n")

        f.write("\n# Faces  (v/vt/vn)\n")
        for face in faces:
            v0, v1, v2, ni, t0, t1, t2 = face
            f.write(f"f {v0}/{t0}/{ni} {v1}/{t1}/{ni} {v2}/{t2}/{ni}\n")

    print(f"Written {len(verts)} vertices, {len(faces)} triangles → {out_path}")
    print(f"({args.count} blades × 2 triangles = {args.count*2} triangles total)")


if __name__ == "__main__":
    main()
