"""
gen_grass_billboards.py — procedural grass billboard OBJ generator

Places N upright quads randomly over a patch (Z-up, ground at Z=0).
Each billboard:
  - Faces in a random azimuth direction (rotated around Z)
  - Slight random tilt (±15°) for variety
  - Random scale variation (±20%)
  - UVs mapped 0-1 across the quad

Usage:
    python scripts/gen_grass_billboards.py [--count 400] [--patch 4.0] \
        [--width 0.3] [--height 0.5] [--seed 42]
    Output: assets/meshes/grass_billboards.obj
"""

import math
import random
import argparse
import os


def normalize(v):
    l = math.sqrt(sum(x * x for x in v))
    return tuple(x / l for x in v) if l > 1e-10 else v


def cross(a, b):
    return (a[1]*b[2] - a[2]*b[1],
            a[2]*b[0] - a[0]*b[2],
            a[0]*b[1] - a[1]*b[0])


def tri_normal(v0, v1, v2):
    e1 = tuple(v1[i] - v0[i] for i in range(3))
    e2 = tuple(v2[i] - v0[i] for i in range(3))
    return normalize(cross(e1, e2))


def generate_billboards(count, patch_size, base_width, base_height, seed):
    rng = random.Random(seed)
    half = patch_size / 2.0

    verts = []
    normals = []
    uvs = []
    faces = []

    for _ in range(count):
        px = rng.uniform(-half, half)
        py = rng.uniform(-half, half)

        # Random azimuth: each billboard faces a random horizontal direction
        theta = rng.uniform(0, 2 * math.pi)
        # Width direction is perpendicular to the facing direction in XY
        wx = -math.sin(theta)
        wy =  math.cos(theta)

        # Random tilt around the width axis (±15°)
        tilt = rng.uniform(-0.26, 0.26)  # radians
        # Tilt moves the tip: tip_offset = sin(tilt) * height along facing dir
        tip_dx = math.cos(theta) * math.sin(tilt)
        tip_dy = math.sin(theta) * math.sin(tilt)
        tip_dz = math.cos(tilt)   # Z component of tip after tilt

        # Scale variation ±20%
        scale = rng.uniform(0.8, 1.2)
        w = base_width  * scale
        h = base_height * scale

        hw = w / 2.0

        # 4 quad vertices
        bl = (px - wx*hw,            py - wy*hw,            0.0)
        br = (px + wx*hw,            py + wy*hw,            0.0)
        tr = (px + wx*hw + tip_dx*h, py + wy*hw + tip_dy*h, tip_dz*h)
        tl = (px - wx*hw + tip_dx*h, py - wy*hw + tip_dy*h, tip_dz*h)

        n_fwd = normalize((math.cos(theta), math.sin(theta), 0.0))
        n = normalize(cross(
            (br[0]-bl[0], br[1]-bl[1], br[2]-bl[2]),
            (tl[0]-bl[0], tl[1]-bl[1], tl[2]-bl[2]),
        ))

        vi = len(verts) + 1
        ni = len(normals) + 1
        ti = len(uvs) + 1

        verts  += [bl, br, tr, tl]
        normals += [n]
        uvs    += [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]

        faces.append((vi+0, vi+1, vi+2, ni, ti+0, ti+1, ti+2))
        faces.append((vi+0, vi+2, vi+3, ni, ti+0, ti+2, ti+3))

    return verts, normals, uvs, faces


def main():
    parser = argparse.ArgumentParser(description="Generate grass billboard OBJ")
    parser.add_argument("--count",  type=int,   default=400,
                        help="Number of billboard quads")
    parser.add_argument("--patch",  type=float, default=4.0,
                        help="Patch side length (m)")
    parser.add_argument("--width",  type=float, default=0.30,
                        help="Base billboard width (m)")
    parser.add_argument("--height", type=float, default=0.50,
                        help="Base billboard height (m)")
    parser.add_argument("--seed",   type=int,   default=42)
    parser.add_argument("--output", type=str,
                        default=os.path.join(os.path.dirname(__file__),
                                             "..", "assets", "meshes",
                                             "grass_billboards.obj"))
    args = parser.parse_args()

    print(f"Generating {args.count} billboards over {args.patch}m patch "
          f"({args.width}m × {args.height}m, seed={args.seed})...")
    verts, normals, uvs, faces = generate_billboards(
        args.count, args.patch, args.width, args.height, args.seed)

    out_path = os.path.normpath(args.output)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Procedural grass billboards — generated by gen_grass_billboards.py\n")
        f.write(f"# {args.count} quads, {args.patch}m patch, "
                f"{args.width}m x {args.height}m, seed {args.seed}\n")
        f.write("o grass_billboards\n\n")
        f.write("# Vertices\n")
        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n# Normals\n")
        for n in normals:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        f.write("\n# UVs\n")
        for uv in uvs:
            f.write(f"vt {uv[0]:.4f} {uv[1]:.4f}\n")
        f.write("\n# Faces  (v/vt/vn)\n")
        for face in faces:
            v0, v1, v2, ni, t0, t1, t2 = face
            f.write(f"f {v0}/{t0}/{ni} {v1}/{t1}/{ni} {v2}/{t2}/{ni}\n")

    print(f"Written {len(verts)} vertices, {len(faces)} triangles → {out_path}")


if __name__ == "__main__":
    main()
